src/Entity/User.php
<?php

namespace App\Entity;

use App\Enum\Role;
use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User extends BaseUser
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    protected $id = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $lastname = null;

    #[ORM\Column]
    private ?bool $admin = null;

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): string
    {
        return implode(' ', array_filter([
            $this->getFirstname(),
            $this->getLastname()
        ]));
    }

    public function isAdmin(): ?bool
    {
        return $this->admin;
    }

    public function setAdmin(bool $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = parent::getRoles();

        if ($this->isAdmin()) {
            $roles[] = Role::ROLE_ADMIN->value;
        }

        return $roles;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }
}

templates/.components/cards/brief_list-card.html.twig
{% extends "@component/card.html.twig" %}

{% set card_classes = ['card-briefs'] | merge(this.cardClasses is defined ? [this.cardClasses] : []) %}

{% block card_header %}
    {% trans %}Additional time{% endtrans %}
{% endblock %}

{% block card_body %}
    <div class="h-100 d-flex flex-column">
        {% for brief in this.briefs %}
            <a href="{{ path('app_node_brief', { slug: brief.slug }) }}" class="card-row flex-grow-1 d-flex flex-row align-items-center text-body">
                <small class="date text-muted mr-1 text-nowrap">
                    {% if brief.publishedAt | date('Ymd') == "now" | date('Ymd') %}
                        {{ brief.publishedAt | date('H:i') }}
                    {% else %}
                        {{ brief.publishedAt | date('d/m') }}
                    {% endif %}
                </small>
                <div class="category badge badge-secondary text-primary mx-1 text-uppercase">
                    {{ brief.categories.first.shortname }}
                </div>
                <div class="title text-nowrap text-truncate">
                    {{ brief.title }}
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/.components/cards/matchs-card.html.twig
{% extends "@component/card.html.twig" %}

{% set card_classes = ['card-match'] | merge(this.cardClasses is defined ? [this.cardClasses] : []) %}

{% set card_body_classes = ['d-flex flex-column'] %}

{% set card_footer_classes = ['p-0'] %}

{% block card_header %}
    Matchs pros
{% endblock %}

{% block card_body %}
    <div x-data="{opened: 'last'}">
        <div class="card-title d-flex flex-row card-title-tab">
            <button class="btn border border-0 flex-grow-1 text-center p-3 tab w-50 btn-previous-game"
                    @click="opened = 'last'"
                    :class="opened == 'last' ? 'active' : ''">
                Dernier match
            </button>
            <button class="btn border border-0 flex-grow-1 text-center p-3 tab w-50 btn-next-game"
                    @click="opened = 'next'"
                    :class="opened == 'next' ? 'active' : ''">
                Prochain match
            </button>
        </div>
        <div class="card-match-body flex-grow-1">
            <div class="flex-column justify-content-center h-100 previous-game" :class="opened == 'last' ? 'd-flex' : 'd-none'">
                {% if this.previousGame() is defined and this.previousGame() is not null %}
                    <small class="text-center text-muted text-uppercase">
                        {{ this.previousGame().date | date('d/m/Y H:i:s') }}
                    </small>
                    <div class="flex-grow-1 d-flex flex-row align-items-center">
                        <div class="flex-grow-1 text-end w-50 {{ this.previousGame().isPlayed ? 'me-1' : 'me-2' }}">
                            <span class="font-weight-bold d-inline d-lg-none d-xl-inline">{{ this.previousGame().teamHome.club.name }}</span>
                            {{ sonata_media(this.previousGame().teamHome.club.logo, 'thumbnail', {
                                alt: this.previousGame().teamHome.club.name,
                            }) }}
                            <span class="font-weight-bold">{{ this.previousGame().scoreHome }}</span>
                        </div>
                        {% if this.previousGame().isPlayed %}
                            <span class="d-inline-block mx-1">-</span>
                        {% endif %}
                        <div class="flex-grow-1 text-start w-50 {{ this.previousGame().isPlayed ? 'ms-1' : 'ms-2' }}">
                            <span class="font-weight-bold">{{ this.previousGame().scoreOutside }}</span>
                            {{ sonata_media(this.previousGame().teamOutside.club.logo, 'thumbnail', {
                                alt: this.previousGame().teamOutside.club.name,
                            }) }}
                            <span class="font-weight-bold d-inline d-lg-none d-xl-inline">{{ this.previousGame().teamOutside.club.name }}</span>
                        </div>
                    </div>
                {% else %}
                    <p class="text-center text-muted m-0">
                        Aucun match
                    </p>
                {% endif %}
            </div>
            <div class="flex-column justify-content-center h-100 next-game" :class="opened == 'next' ? 'd-flex' : 'd-none'">
                {% if this.nextGame() is defined and this.nextGame() is not null %}
                    <small class="text-center text-muted text-uppercase">
                        {{ this.nextGame().date | date('d/m/Y H:i:s') }}
                    </small>
                    <div class="flex-grow-1 d-flex flex-row align-items-center">
                        <div class="flex-grow-1 text-end w-50 me-2">
                            <span class="font-weight-bold d-inline d-lg-none d-xl-inline">{{ this.nextGame().teamHome.club.name }}</span>
                            {{ sonata_media(this.nextGame().teamHome.club.logo, 'thumbnail', {
                                alt: this.nextGame().teamHome.club.name,
                            }) }}
                        </div>
                        <div class="flex-grow-1 text-start w-50 ms-2">
                            {{ sonata_media(this.nextGame().teamOutside.club.logo, 'thumbnail', {
                                alt: this.nextGame().teamOutside.club.name,
                            }) }}
                            <span class="font-weight-bold d-inline d-lg-none d-xl-inline">{{ this.nextGame().teamOutside.club.name }}</span>
                        </div>
                    </div>
                {% else %}
                    <p class="text-center text-muted m-0">
                        Pas encore de match
                    </p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/.components/cards/poll-card.html.twig
{# TODO HTML du composant affichant le sondage #}

templates/.components/cards/post-card.html.twig
{% extends "@component/card.html.twig" %}

{% set card_classes = ['card-post'] | merge(this.cardClasses is defined ? [this.cardClasses] : []) %}
{% set card_footer_classes = ['d-flex flex-row justify-content-between'] %}

{% block card_content %}
    {{ sonata_media(post.image, mediaFormat, {
        class: 'card-img-top',
        alt: post.title,
        picture: {
            '(max-width: 767px)': 'card_mobile',
        },
    }) }}

    <div class="card-body">
        <h5 class="lead">{{ post.title }}</h5>
        <div class="card-text categories">
            {{ post.categories | map(c => c.name) | join(' / ') }}
        </div>
    </div>
{% endblock %}

{% block card_footer %}
    <small class="text-muted">
        {{ post.publishedAt | date('d/m') }}
    </small>
    <small class="text-muted">
        {{ post.author.fullname }}
    </small>
{% endblock %}